// Central registry for all calculators: label, description, route names, card styling
export const calculatorsRegistry = [
  {
    key: 'das28',
    name: 'DAS28 (RA activity)',
    desc: '28-joint disease activity score (ESR/CRP variants).',
    badge: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    card: 'bg-white border-indigo-200/70 hover:border-indigo-300 hover:bg-indigo-50/40',
    routeShow: 'doctor.patients.calculators.das28',
    routeStore: 'doctor.patients.calculators.das28.store',
  },
  {
    key: 'cdai',
    name: 'CDAI',
    desc: 'TJC28 + SJC28 + Patient global (0–10) + Physician global (0–10).',
    badge: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    card: 'bg-white border-emerald-200/70 hover:border-emerald-300 hover:bg-emerald-50/40',
    routeShow: 'doctor.patients.calculators.cdai',
    routeStore: 'doctor.patients.calculators.cdai.store',
  },
  {
    key: 'sdai',
    name: 'SDAI',
    desc: 'CDAI + CRP (mg/dL).',
    badge: 'bg-sky-100 text-sky-800 border-sky-200',
    card: 'bg-white border-sky-200/70 hover:border-sky-300 hover:bg-sky-50/40',
    routeShow: 'doctor.patients.calculators.sdai',
    routeStore: 'doctor.patients.calculators.sdai.store',
  },
  {
    key: 'basdai',
    name: 'BASDAI',
    desc: 'AS disease activity (6 VAS questions, 0–10).',
    badge: 'bg-amber-100 text-amber-900 border-amber-200',
    card: 'bg-white border-amber-200/70 hover:border-amber-300 hover:bg-amber-50/40',
    routeShow: 'doctor.patients.calculators.basdai',
    routeStore: 'doctor.patients.calculators.basdai.store',
  },
  {
    key: 'asdas_crp',
    name: 'ASDAS-CRP',
    desc: 'Objective AS activity index (includes CRP).',
    badge: 'bg-fuchsia-100 text-fuchsia-800 border-fuchsia-200',
    card: 'bg-white border-fuchsia-200/70 hover:border-fuchsia-300 hover:bg-fuchsia-50/40',
    routeShow: 'doctor.patients.calculators.asdas_crp',
    routeStore: 'doctor.patients.calculators.asdas_crp.store',
  },
  {
    key: 'haqdi',
    name: 'HAQ-DI',
    desc: 'Disability index (simple average of answers, 0–3).',
    badge: 'bg-slate-100 text-slate-800 border-slate-200',
    card: 'bg-white border-slate-200/70 hover:border-slate-300 hover:bg-slate-50/40',
    routeShow: 'doctor.patients.calculators.haqdi',
    routeStore: 'doctor.patients.calculators.haqdi.store',
  },
  {
    key: 'dapsa',
    name: 'DAPSA',
    desc: 'PsA activity: TJC68 + SJC66 + Pain + PtGlobal + CRP.',
    badge: 'bg-rose-100 text-rose-800 border-rose-200',
    card: 'bg-white border-rose-200/70 hover:border-rose-300 hover:bg-rose-50/40',
    routeShow: 'doctor.patients.calculators.dapsa',
    routeStore: 'doctor.patients.calculators.dapsa.store',
  },
  {
    key: 'vas',
    name: 'VAS (0–100)',
    desc: 'Generic patient VAS (pain/fatigue/global).',
    badge: 'bg-cyan-100 text-cyan-800 border-cyan-200',
    card: 'bg-white border-cyan-200/70 hover:border-cyan-300 hover:bg-cyan-50/40',
    routeShow: 'doctor.patients.calculators.vas',
    routeStore: 'doctor.patients.calculators.vas.store',
  },
  {
    key: 'bmi',
    name: 'BMI',
    desc: 'Weight/height with WHO banding.',
    badge: 'bg-lime-100 text-lime-800 border-lime-200',
    card: 'bg-white border-lime-200/70 hover:border-lime-300 hover:bg-lime-50/40',
    routeShow: 'doctor.patients.calculators.bmi',
    routeStore: 'doctor.patients.calculators.bmi.store',
  },
  {
    key: 'eular_resp',
    name: 'EULAR Response',
    desc: 'Response based on ΔDAS28 + current DAS28.',
    badge: 'bg-purple-100 text-purple-800 border-purple-200',
    card: 'bg-white border-purple-200/70 hover:border-purple-300 hover:bg-purple-50/40',
    routeShow: 'doctor.patients.calculators.eular_resp',
    routeStore: 'doctor.patients.calculators.eular_resp.store',
  },
];
